### ISSUE TITLE
No default DynamoFormat for Byte or Byte[] in scanamo causes error

### ISSUE THREAD

**Issue by drocsid** [guardian/scanamo-scrooge#4]
Recently I tried following the example using my own custom scrooge generated classes. I think this would be the most common way anyone would approach using this for their own purposes:

```
scala> import com.gu.scanamo._
import com.gu.scanamo._

scala> import com.gu.scanamo.scrooge.ScroogeDynamoFormat._
import com.gu.scanamo.scrooge.ScroogeDynamoFormat._

scala> import com.example.api._
import com.example.api._

scala> val authorDetails = AuthorDetails("http://somewebsite.com",Some(234))
authorDetails: com.example.AuthorDetails = AuthorDetails(http://somewebsite.com,Some(234),None,None,None,None,None,None,None,None,None,None,None,None,None,None,None)

scala> DynamoFormat[AuthorDetails].write(authorDetails)
<console>:26: error: could not find Lazy implicit value of type com.gu.scanamo.DynamoFormat[Option[Byte]]
       DynamoFormat[AuthorDetails].write(authorDetails)
```

I made a google search and found:

```
guardian/scanamo-scrooge - Travis CI
https://travis-ci.org/guardian/scanamo-scrooge
Travis CI
Jul 21, 2016 - [info] Updating {file:/home/travis/build/guardian/scanamo-scrooge/project/}scanamo-scrooge-build. ..... could not find Lazy implicit value of type com.gu.scanamo.DynamoFormat[com.gu.contentatom.thrift.atom.media.
You've visited this page 3 times. Last visit: 8/8/16
```

Is this related to  https://github.com/guardian/scanamo-scrooge/pull/1 ?

**Comment by philwills** [comment]
This isn't related to #1, but I think down to the fact that there's currently no default `DynamoFormat` for `Byte` in https://github.com/guardian/scanamo/blob/master/src/main/scala/com/gu/scanamo/DynamoFormat.scala 

If you'd like to have a go at a PR, https://github.com/guardian/scanamo/pull/53/files might give you some idea of how, or failing that if you could open an issue on the main Scanamo repo, I'll try and add one.

**Comment by drocsid** [comment]
@philwills  I can have a shot as suggested. But I'm a Java refugee and new to Scala... Will update my progress by EOD.

**Comment by philwills** [comment]
OK, it's not a big thing for me to do, so if you're struggling, don't worry about it. I'm planning to do some releases this week, once the new version of  [cats](https://github.com/typelevel/cats), which is one of the dependencies is out.

**Comment by drocsid** [comment]
Gonna give it a shot regardless. Thought it might be related to this line:

https://github.com/guardian/scanamo-scrooge/blob/master/src/main/scala/com/gu/scanamo/scrooge/ScroogeDynamoFormat.scala#L52

**Comment by drocsid** [comment]
It doesn't appear that Amazons' AttributeValue provides a Byte instance, but thrift does. However it does appear to have a ByteBuffer instance.. Then what makes might sense to me would be mapping Byte => ByteBuffer, assuming that this is less expensive than using strings.

Furthermore, now might be a good time to map Byte[] => ByteBuffer, since thrift also supports a binary storage class.

I have thought about implementing  [[DynamoFormat.coercedXmap]] or [[DynamoFormat.xmap]] based on source code comments, but I'm a scala novice...

Looking at some examples here's what I tried so far:

```
private val javaByteBufferFormat = attribute[java.nio.ByteBuffer](_.getB, "B")(_.withB)

  using ByteBuffer
  implicit val byteFormat = xmap[Byte, java.nio.ByteBuffer](
    b => Xor.right(Byte.unbox(b)))(
    //Byte[Byte.box]
  )(javaByteBufferFormat)

```

Going to mess around a little longer today to see if I can figure out anything that works.

**Comment by drocsid** [comment]
Based on your suggestions I was trying something like

```
 private val javaByteBufferFormat = attribute(_.getB, "B")(_.withB)
 private def coerceByteArray[B](f: Array[Byte] => B): Array[Byte] => Xor[DynamoReadError, B] =
    coerce[Array[Byte],B, IllegalArgumentException](f)

  implicit val binaryFormat = xmap(coerceByteArray(...
```

But I'm lost defining the conversion binaryFormat. I'm sort of lost in the scala functional world. Then this underscores that I need to learn more regarding the language. However do you have any suggestions or should I just wait to look at your solution later this week?

**Comment by drocsid** [comment]
Looks like the PR fixed the issue, closing this!
